# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, configurator, filepath, mtl, snap, snapCore, transformers
}:

cabal.mkDerivation (self: {
  pname = "snaplet-sass";
  version = "0.1.0.0";
  sha256 = "0wv9a7pa6r7nzgppbywasqy38zk79ann2ivwyyh2b9dny95mx5yd";
  buildDepends = [
    configurator filepath mtl snap snapCore transformers
  ];
  meta = {
    homepage = "https://github.com/lukerandall/snaplet-sass";
    description = "Sass integration for Snap with request- and pre-compilation";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
